In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

Dataset_path = "/home/ebrahim/Projects/ML_Project/Dataset"

Notes:
1. Required age have no nulls, but 0 values which consider as nulls.
2. Pc requirements, should be converted to operating system and ram, and maybe, maybe, cpu specs not name, also storage can be added, require some analysis and feature engineering.



to be investigated:
1. which to remove and which to keep, IsFree, FreeVerAvail,PurchaseAvail, SubscriptionAvail, PriceInitial, PriceFinal
2. 'DemoCount', 'DeveloperCount', 'DLCCount', 'MovieCount', 'PackageCount', requires investigation also

In [15]:
train_data = pd.read_csv(Dataset_path + '/train_data.csv')
pd.set_option('display.max_columns', None)
train_data.head(15)

,QueryID,ResponseID,QueryName,ResponseName,ReleaseDate,RequiredAge,DemoCount,DeveloperCount,DLCCount,Metacritic,MovieCount,PackageCount,RecommendationCount,PublisherCount,ScreenshotCount,SteamSpyOwners,SteamSpyOwnersVariance,SteamSpyPlayersEstimate,SteamSpyPlayersVariance,AchievementCount,AchievementHighlightedCount,ControllerSupport,IsFree,FreeVerAvail,PurchaseAvail,SubscriptionAvail,PlatformWindows,PlatformLinux,PlatformMac,PCReqsHaveMin,PCReqsHaveRec,LinuxReqsHaveMin,LinuxReqsHaveRec,MacReqsHaveMin,MacReqsHaveRec,CategorySinglePlayer,CategoryMultiplayer,CategoryCoop,CategoryMMO,CategoryInAppPurchase,CategoryIncludeSrcSDK,CategoryIncludeLevelEditor,CategoryVRSupport,GenreIsNonGame,GenreIsIndie,GenreIsAction,GenreIsAdventure,GenreIsCasual,GenreIsStrategy,GenreIsRPG,GenreIsSimulation,GenreIsEarlyAccess,GenreIsFreeToPlay,GenreIsSports,GenreIsRacing,GenreIsMassivelyMultiplayer,PriceCurrency,PriceInitial,PriceFinal,SupportEmail,SupportURL,AboutText,Background,ShortDescrip,DetailedDescrip,DRMNotice,ExtUserAcctNotice,HeaderImage,LegalNotice,Reviews,SupportedLanguages,Website,PCMinReqsText,PCRecReqsText,LinuxMinReqsText,LinuxRecReqsText,MacMinReqsText,MacRecReqsText
0,10,10,Counter-Strike,Counter-Strike,Nov 1 2000,0,0,1,0,88,0,1,68991,1,13,13033334,92789,9140731,78136,0,0,False,False,False,True,False,True,True,True,True,False,True,False,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,9.99,9.99,,http://steamcommunity.com/app/10,Play the worlds number 1 online action game. E...,http://cdn.akamai.steamstatic.com/steam/apps/1...,,Play the worlds number 1 online action game. E...,,,http://cdn.akamai.steamstatic.com/steam/apps/1...,,,English French German Italian Spanish Simplifi...,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
1,20,20,Team Fortress Classic,Team Fortress Classic,Apr 1 1999,0,0,1,0,0,0,1,2439,1,5,5399140,60368,753627,22699,0,0,False,False,False,True,False,True,True,True,True,False,True,False,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,4.99,4.99,,,One of the most popular online action games of...,http://cdn.akamai.steamstatic.com/steam/apps/2...,,One of the most popular online action games of...,,,http://cdn.akamai.steamstatic.com/steam/apps/2...,,,English French German Italian Spanish,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
2,30,30,Day of Defeat,Day of Defeat,May 1 2003,0,0,1,0,79,0,1,2319,1,5,7621102,71499,1709740,34145,0,0,False,False,False,True,False,True,True,True,True,False,True,False,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,4.99,4.99,,,Enlist in an intense brand of Axis vs. Allied ...,http://cdn.akamai.steamstatic.com/steam/apps/3...,,Enlist in an intense brand of Axis vs. Allied ...,,,http://cdn.akamai.steamstatic.com/steam/apps/3...,,,English French German Italian Spanish,http://www.dayofdefeat.com/,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
3,40,40,Deathmatch Classic,Deathmatch Classic,Jun 1 2001,0,0,1,0,0,0,1,888,1,4,7498965,70936,789676,23235,0,0,False,False,False,True,False,True,True,True,True,False,True,False,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,4.99,4.99,,,Enjoy fast-paced multiplayer gaming with Death...,http://cdn.akamai.steamstatic.com/steam/apps/4...,,Enjoy fast-paced multiplayer gaming with Death...,,,http://cdn.akamai.steamstatic.com/steam/apps/4...,,,English French German Italian Spanish,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
4,50,50,Half-Life: Opposing Force,Half-Life: Opposing Force,Nov 1 1999,0,0,1,0,0,0,1,2934,1,5,5399499,60370,705741,21968,0,0,False,False,False,True,False,True,True,True,True,False,True,False,True,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,4.99,4.99,,,Return to the Black Mesa Research Facility as ...,http://cdn.akamai.steamstatic.com/steam/apps/5...,,Return to the Black Mesa Research Facility as ...,,,http://cdn.akamai.steamstatic.com/steam/apps/5...,,,English French German Korean,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
5,60,60,Ricochet,Ricochet,Nov 1 2000,0,0,1,0,0,0,1,1965,1,4,7488563,70888,843481,24011,0,0,False,False,False,True,False,True,True,True,True,False,True,False,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,4.99,4.99,,,A futuristic action game that challenges your ...,http://cdn.akamai.steamstatic.com/steam/apps/6...,,A futuristic action game that challenges your ...,,,http://cdn.akamai.steamstatic.com/steam/apps/6...,,,English French German Italian Spanish,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
6,70,70,Half-Life,Half-Life,Nov 8 1998,0,0,1,1,96,0,1,12486,1,11,5927504,63206,2268772,39303,0,0,False,False,False,True,False,True,True,True,True,False,True,False,True,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,9.99,9.99,,http://steamcommunity.com/app/70,Named Game of the Year by over 50 publications...,http://cdn.akamai.steamstatic.com/steam/apps/7...,,Named Game of the Year by over 50 publications...,,,http://cdn.akamai.steamstatic.com/steam/apps/7...,,,English French German Italian Spanish Simplifi...,http://www.half-life.com/,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
7,80,80,Counter-Strike: Condition Zero,Counter-Strike: Condition Zero,Mar 1 2004,0,0,1,0,65,0,1,7067,1,8,10489261,83543,4127910,52878,0,0,False,False,False,True,False,True,True,True,True,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,9.99,9.99,,http://steamcommunity.com/app/80,With its extensive Tour of Duty campaign a nea...,http://cdn.akamai.steamstatic.com/steam/apps/8...,,With its extensive Tour of Duty campaign a nea...,,,http://cdn.akamai.steamstatic.com/steam/apps/8...,,,English French German Italian Spanish Simplifi...,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,,,,
8,130,130,Half-Life: Blue Shift,Half-Life: Blue Shift,Jun 1 2001,0,0,1,0,71,0,1,2219,1,5,5368650,60199,662517,21286,0,0,False,False,False,True,False,True,True,True,True,False,True,False,True,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,4.99,4.99,,,Made by Gearbox Software and originally releas...,http://cdn.akamai.steamstatic.com/steam/apps/1...,,Made by Gearbox Software and originally releas...,,,http://cdn.akamai.steamstatic.com/steam/apps/1...,,,English French German,NaN,Minimum: 500 mhz processor 96mb ram 16mb video...,,Minimum: Linux Ubuntu 12.04 Dual-core from Int...,,Minimum: OS X Snow Leopard 10.6.3 1GB RAM 4GB...,
9,220,220,Half-Life 2,Half-Life 2,Nov 16 2004,0,1,1,1,96,2,2,35792,1,9,9901173,81234,5695963,61979,33,10,False,False,False,True,False,True,True,True,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,9.99,9.99,,http://steamcommunity.com/app/220,1998. HALF-LIFE sends a shock through the game...,http://cdn.akamai.steamstatic.com/steam/apps/2...,#app_220_note_1,1998. HALF-LIFE sends a shock through the game...,,,http://cdn.akamai.steamstatic.com/steam/apps/2...,,,English* French* German* Italian* Korean* Span...,http://www.half-life2.com,,,,,,
10,240,240,Counter-Strike: Source,Counter-Strike: Source,Nov 1 2004,0,0,1,0,88,0,1,53931,1,5,15433570,100626,11472993,87251,147,10,False,False,False,True,False,True,True,True,True,False,True,False,True,False,False,True,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,19.99,19.99,,http://steamcommunity.com/app/240,THE NEXT INSTALLMENT OF THE WORLDS # 1 ONLINE ...,http://cdn.akamai.steamstatic.com/steam/apps/2...,Just updated to include player stats achieveme...,THE NEXT INSTALLMENT OF THE WORLDS # 1 ONLINE ...,,,http://cdn.akamai.steamstatic.com/steam/apps/2...,,,English French German Italian Japanese Korean ...,NaN,Minimum: 1.7 GHz Processor 512MB RAM DirectX® ...,,Minimum: 1.7 GHz Processor 512MB RAM Mouse Key...,,Minimum: OS X version Leopard 10.5.8 Snow Leop...,
11,280,280,Half-Life: Source,Half-Life: Source,Jun 1 2004,0,0,1,0,0,0,1,2547,1,4,2983660,45027,695697,21811,0,0,False,True,False,True,False,True,True,True,True,False,True,False,True,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,9.99,9.99,,,Winner of over 50 Game of the Year awards Half...,http://cdn.akamai.steamstatic.com/steam/apps/2...,,Winner of over 50 Game of the Year awards Half...,,,http://cdn.akamai.steamstatic.com/steam/apps/2...,,,English French German Italian Japanese Spanish...,NaN,Minimum: 1.2 GHz Processor 256MB RAM DirectX 7...,,Minimum: OS: Ubuntu 12.04Processor: Dual core ...,,Minimum: OS:OS X version Leopard 10.5.8 Snow L...,
12,300,300,Day of Defeat: Source,Day of Defeat: Source,Jul 12 2010,0,0,1,0,80,3,1,7185,1,5,6400269,65635,2895778,44364,54,10,False,False,False,True,False,True,True,True,True,False,False,False,True,False,False,True,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,9.99,9.99,,,Day of Defeat offers intense online action gam...,http://cdn.akamai.steamstatic.com/steam/apps/3...,#app_300_note_1,Day of Defeat offers intense online action gam...,,,http://cdn.akamai.steamstatic.com/steam/apps/3...,,,English,http://www.dayofdefeat.com/,Minimum: 1.7 GHz Processor 512MB RAM DirectX® ...,,,,Minimum: OS X version Leopard 10.5.8 Snow Leop...,
13,340,340,Half-Life 2: Lost Coast,Half-Life 2: Lost Coast,Oct 27 2005,0,0,1,0,0,0,0,4352,1,5,14844765,98771,2885376,44285,0,0,False,True,False,False,False,True,True,True,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,,0.00,0.00,,,Originally planned as a section of the Highway...,http://cdn.akamai.steamstatic.com/steam/apps/3...,,Originally planned as a section of the Highway...,,,http://cdn.akamai.steamstatic.com/steam/apps/3...,,,English French German Italian Spanish Russian ...,http://www.half-life2.com,Minimum: Pentium 4 2.4GHz or AMD 2800+ Process...,,,,,
14,360,360,Half-Life Deathmatch: Source,Half-Life Deathmatch: Source,May 1 2006,0,0,1,0,0,0,1,864,1,5,6796273,67597,388292,16301,0,0,False,True,False,True,False,True,True,True,True,False,True,False,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,USD,9.99,9.99,,,Half-Life Deathmatch: Source is a recreation o...,http://cdn.akamai.steamstatic.com/steam/apps/3...,,Half-Life Deathmatch: Source is a recreation o...,,,http://cdn.akamai.steamstatic.com/steam/apps/3...,,,English,NaN,Minimum:OS: Windows(r) 7 (32/64-bit)/Vista/XPP...,,Minimum:OS: Ubuntu 12.04Processor: Dual core f...,,Minimum:OS: OS X 10.5.8Processor: Dual core fr...,

In [19]:
url_pattern = r'^(https?://)?(www\.)?([a-zA-Z0-9-]+)\.([a-zA-Z]{2,})(/[^\s]*)?$'
date_pattern = r'^\d{4}-\d{2}-\d{2}$'
columns = train_data.columns
url_or_date_columns = [col for col in columns if train_data[col].astype(str).str.match(url_pattern).any() or train_data[col].astype(str).str.match(date_pattern).any()]
print("Columns that likely contain URLs or dates:", url_or_date_columns)
needed_columns = [col for col in columns if col not in url_or_date_columns]

Columns that likely contain URLs or dates: ['QueryName', 'ResponseName', 'ReleaseDate', 'SupportEmail', 'SupportURL', 'ExtUserAcctNotice', 'LegalNotice', 'Website']

In [23]:
train_data['RequiredAge'].value_counts()

RequiredAge
0     10777
17      381
13       70
18       65
16       35
15        9
10        9
12        7
14        1
1         1
6         1
7         1
Name: count, dtype: int64

In [24]:
train_data['LegalNotice'].value_counts()

LegalNotice
                                                                                                                                                                                                                                    6664
(c) 2016 THQ Nordic GmbH; THQ Nordic GmbH is a wholly owned publishing subsidiary of THQ Nordic AB. The THQ Nordic logo and the THQ Nordic symbol are registered trademarks or trademarks of THQ Nordic AB. All rights reserved.      23
(c) Disney                                                                                                                                                                                                                            22
(c)2014 Tommo Inc. All rights reserved. RETROISM(r) and the RETROISM(r) logo are trademarks or registered trademarks of Tommo Inc. All other trademarks are properties of their respective owners.                                    21
(c) 2014 Artifex Mundi sp. z o.o. All rights reserved. Artifex Mundi is a trademark of Artifex Mundi. All registered trademarks are the property of their respective owners.                                                          18
                                                                                                                                                                                                                                    ...
Space Tyrant (c) 2016 Blue Wizard Digital Inc. Space Tyrant and the Space Tyrant Logo are registered trademarks or trademarks of Blue Wizard Digital Inc. All rights reserved.                                                         1
(c) 2017 Lukas Jaeckel.                                                                                                                                                                                                                1
Guardian Arena uses the Unreal(r) Engine. Unreal(r) is a trademark or registered trademark of Epic Games Inc. in the United States of America and elsewhere.                                                                           1
(C) 2016 Tatyana Murzina                                                                                                                                                                                                               1
2016 copyright by netmin e.K.                                                                                                                                                                                                          1
Name: count, Length: 4037, dtype: int64

In [42]:
train_data['ShortDescrip'].value_counts()

ShortDescrip
                                                                                                                                                                                                                                                                1577
Ever dreamed of driving trains? Now you can!  Train Simulator 2016 brings to life some amazing extreme train challenges on real world routes and delivers the ultimate railway hobby.                                                                              8
Experience the original F.E.A.R. along with  F.E.A.R. Extraction Point and F.E.A.R. Perseus Mandate.  Available Now!                                                                                                                                               4
You decide the combat role you want to assume in the world of Brink as you fight to save yourself and mankinds last refuge!                                                                                                                                        4
Tom Clancys Rainbow Six Siege is the upcoming installment of the acclaimed first-person shooter franchise developed by the renowned Ubisoft Montreal studio.                                                                                                       4
                                                                                                                                                                                                                                                                ...
TILE is a minimalist puzzle game with relaxing soundtrack.                                                                                                                                                                                                         1
Start a baseball riot! Help Gabe Carpaccio take vengeance on the unholy alliance of his former team and a corrupt energy drink manufacturer Explodz Inc. in this fun physics based puzzle game! Baseball Riot is a sequel to Tennis in the Face.                   1
Passage 4 puts all the best parts of classic board games in one place.                                                                                                                                                                                             1
Piximalism - hardcore platformer with beautiful pixel graphics. Beware of enemies and spikes. Try your skills! Many difficult levels are waiting for you!                                                                                                          1
Ghostlight Manor is a strategic puzzler with a brand new mechanic featuring 56 progressively challenging levels and a cast of beloved classic monsters. Explore a treacherous and haunted countryside to locate the mysterious source of a monster invasion!       1
Name: count, Length: 9718, dtype: int64

In [44]:
train_data['DetailedDescrip'].value_counts()

DetailedDescrip
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    580
Special EditionTrain Simulator: UK First Class Edition content TS Academy Riviera Line: Exeter - Kingswear route featuring the GWR Castle Class Steam Engine Midland Main Line: London - Bedford route featuring the First Capital Connect Class 319 and Great Eastern Main Line: London - Ipswich route featuring the Greater Anglia Class 360. Also includes the bonus Double Chimney GWR Castle Class and Wartime Black GWR Castle Class steam engines.Train Simulator: US First Class Edition content TS Academy Sherman Hill route featuring the iconic UP Gas Turbine loco Miami - West Palm Beach route featuring the CSX Dash 8-40CW Soldier Summit route featuring the D&RGW SD40T-2. Also includes the bonus UP SD60M loco UP Insulated 50-foot RBL Plug Door Boxcar and Military Flatcars.Train Simulator: German First Class Edition content TS Academy West Rhine: Cologne - Koblenz route featuring the DB BR 155 electric loco Munich - Rosenheim route featuring the DB BR 423 Munich Augsburg route featuring the DB BR 406 ICE 3M. Also includes the bonus PRESS BR 155 electric loco and military flat wagons.About the GameEnjoy three fantastic real-world routes including Sherman Hill (USA) Riviera Line: Exeter to Kingswear (UK) and West Rhine: Cologne to Koblenz (Germany). Train Simulator 2016 is the biggest package of exclusive content we have ever delivered in a Train Simulator!EXCLUSIVE Steam Edition includes the additional route Norfolk Southern Coal District route.Feel the pressure of steam as you travel back to the time of Green and Gold from the powerful Kings to the romantic Castles the heavy working Halls the goods-carrying Granges and the famous Pannier Tanks across the Riviera Line set in the nostalgic 1950s. Relive the time when steam reigned on all services from local freight to coastline express whether you perform perfectly alone or need some assistance to get to your destination. The 40 Mile Riviera Line in the 1950s comes with GWR Pannier Tank Castle Hall King and Grange Class all with Driver Assist incorporated Mk1 Collett and Centenary coaches and freight wagons. Keep an eye on those signals they can be easy to lose in the cold western fog.Experience the power of the fuel-hungry Big Blows across the challenging Sherman Hill as you haul hundreds upon hundreds of tons putting that 8500 horsepower turbine through its paces or opt for some conventional traction in the form of ES44ACs drive in more comfortable conditions in the wide cab of the SD70M or maybe in the classic SD40-2s.  The 60 Mile Sherman Hill route comes with UP Gas Turbine ES44AC SD70 SD40 and SW10 locomotives and freight wagons. Watch out though winter can be brutal even for the most powerful of locos.Control the Genesis of modern Electro-motive traction as you haul heavy freight across the stunning West Rhine Railway in the DB BR 155 Electric Container take passengers on their scenic commute with the DB BR 146 or shunt together a train to be taken far away with the DB BR 294. The 60 Mile West Rhine Railway from Cologne to Koblenz comes with DB BR 155 146.0 146.2 101 and 294 with regional and InterCity coaches and a variety of freight wagons. Be mindful of the weather heavy rain can take even the best drivers by surprise. Struggle through the beautifully scenic Mon Line as you haul mile long coal trains through the winding curves and streets of Pennsylvania. Collect coal as you drive your ES44AC slowly under the loading facilities and prepare for the run to the other end of the line. While being relatively level the sharp river-side turns and the slow speeds as you cut right through a town will not be mastered easily. The 50 Mile Norfolk Southern Coal District route comes with Norfolk Southern ES44AC and Dash 9 (AI Only) locomotives with NS coal hoppers. (Only available with Steam Edition)Capture the perfect scenes in the all new Railfan mode Enjoy the power and finesse of the railway away from the drivers cab with railfan mode watch from the platform track side or stand on a bridge and take in the excitement without worrying about the journey just make sure youre ready to take some shots you never know what you might see out on the tracks!Learn to drive different trains at the TS Academy and qualify as a train driver New to driving trains? Not to worry! With the newly updated TS Academy you can learn all that you need to beat the extreme from basic passenger operations to freight terminals that require pin-point accuracy or nailing those complex and unique signalling systems. TS academy is the best way to learn or remember how to control every type of trainHave you mastered driving diesel and electric locos but struggled to control steam? Found it too complicated to drive or understand? Now you can master these delicate engines with our all new driving assist! Driver assist will provide you with real time information based on the locomotives performance and handling it will guide you through driving a steam loco by highlighting the controls in cab and telling you how to move them to get the best out of the engine. Driver Assist is featured on all the steam locomotives included with the Riviera Line in the Fifties route and can be turned on and off at will.Additional Features: Enhanced graphics and performance Quick Drive menu system: drive what you like where you like Drive with Xbox 360 controller keyboard or mouse Integrated Steam Workshop free mission download centre Create your own routes with powerful in-game editing tools Access the Train Simulator community in-game      8
The small country of Arulco has been taken over by a merciless dictator - and only you can loosen the iron grip! Jagged Alliance 2 Gold Pack immerses you into an elaborate role-playing universe where you will interact with more than 150 characters recruit your own band of soldiers and create your own custom mercenary to win back Arulco - not once but twice! The perfect blend of strategy role playing and tactical combat!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               5

In [29]:
train_data['AboutText'].value_counts()

AboutText
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     583
Enjoy three fantastic real-world routes including Sherman Hill (USA) Riviera Line: Exeter to Kingswear (UK) and West Rhine: Cologne to Koblenz (Germany). Train Simulator 2016 is the biggest package of exclusive content we have ever delivered in a Train Simulator!EXCLUSIVE Steam Edition includes the additional route Norfolk Southern Coal District route.Feel the pressure of steam as you travel back to the time of Green and Gold from the powerful Kings to the romantic Castles the heavy working Halls the goods-carrying Granges and the famous Pannier Tanks across the Riviera Line set in the nostalgic 1950s. Relive the time when steam reigned on all services from local freight to coastline express whether you perform perfectly alone or need some assistance to get to your destination. The 40 Mile Riviera Line in the 1950s comes with GWR Pannier Tank Castle Hall King and Grange Class all with Driver Assist incorporated Mk1 Collett and Centenary coaches and freight wagons. Keep an eye on those signals they can be easy to lose in the cold western fog.Experience the power of the fuel-hungry Big Blows across the challenging Sherman Hill as you haul hundreds upon hundreds of tons putting that 8500 horsepower turbine through its paces or opt for some conventional traction in the form of ES44ACs drive in more comfortable conditions in the wide cab of the SD70M or maybe in the classic SD40-2s.  The 60 Mile Sherman Hill route comes with UP Gas Turbine ES44AC SD70 SD40 and SW10 locomotives and freight wagons. Watch out though winter can be brutal even for the most powerful of locos.Control the Genesis of modern Electro-motive traction as you haul heavy freight across the stunning West Rhine Railway in the DB BR 155 Electric Container take passengers on their scenic commute with the DB BR 146 or shunt together a train to be taken far away with the DB BR 294. The 60 Mile West Rhine Railway from Cologne to Koblenz comes with DB BR 155 146.0 146.2 101 and 294 with regional and InterCity coaches and a variety of freight wagons. Be mindful of the weather heavy rain can take even the best drivers by surprise. Struggle through the beautifully scenic Mon Line as you haul mile long coal trains through the winding curves and streets of Pennsylvania. Collect coal as you drive your ES44AC slowly under the loading facilities and prepare for the run to the other end of the line. While being relatively level the sharp river-side turns and the slow speeds as you cut right through a town will not be mastered easily. The 50 Mile Norfolk Southern Coal District route comes with Norfolk Southern ES44AC and Dash 9 (AI Only) locomotives with NS coal hoppers. (Only available with Steam Edition)Capture the perfect scenes in the all new Railfan mode Enjoy the power and finesse of the railway away from the drivers cab with railfan mode watch from the platform track side or stand on a bridge and take in the excitement without worrying about the journey just make sure youre ready to take some shots you never know what you might see out on the tracks!Learn to drive different trains at the TS Academy and qualify as a train driver New to driving trains? Not to worry! With the newly updated TS Academy you can learn all that you need to beat the extreme from basic passenger operations to freight terminals that require pin-point accuracy or nailing those complex and unique signalling systems. TS academy is the best way to learn or remember how to control every type of trainHave you mastered driving diesel and electric locos but struggled to control steam? Found it too complicated to drive or understand? Now you can master these delicate engines with our all new driving assist! Driver assist will provide you with real time information based on the locomotives performance and handling it will guide you through driving a steam loco by highlighting the controls in cab and telling you how to move them to get the best out of the engine. Driver Assist is featured on all the steam locomotives included with the Riviera Line in the Fifties route and can be turned on and off at will.Additional Features: Enhanced graphics and performance Quick Drive menu system: drive what you like where you like Drive with Xbox 360 controller keyboard or mouse Integrated Steam Workshop free mission download centre Create your own routes with powerful in-game editing tools Access the Train Simulator community in-game      8
The small country of Arulco has been taken over by a merciless dictator - and only you can loosen the iron grip! Jagged Alliance 2 Gold Pack immerses you into an elaborate role-playing universe where you will interact with more than 150 characters recruit your own band of soldiers and create your own custom mercenary to win back Arulco - not once but twice! The perfect blend of strategy role playing and tactical combat!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                5
With the completion of the third title in the RIP series the RIP games have become an instant classic in the arcade-shooter genre. RIP — Trilogy brings all three RIP titles into one exciting and heart-pounding pack.RIPNot afraid of Death? What if he is accompanied by Halloween and Rock-N-Roll? Play the part of these antiheroes and go to war in this all-out action experience! Each character has their own strengths and skills but this is not a game for the faint of heart. With over 40 levels to RIP through the results are murderous!40 levels of murder and mayhemA variety of guns and battle magicThree chilling charactersA toned-down less violent kids modeRIP2 — Strike BackYour favorite antiheroes are here to strike back with another score to settle. Death Halloween and Rock-N-Roll...each character has his own strengths and skills so pick one and start shooting. In Story Mode youll fight through 60 furious levels using an arsenal of upgradeable weapons tanks helicopters and turrets or for a quick adrenaline fix play Rush Mode and see how long you can last.Choose from a large arsenal of weaponsAssorted vehicles including gun turrets tanks and helicoptersVariety of abilities and power-ups60 levels of unlimited gameplayHuge boss levels for more challengeTwo modes of play; Rush Mode or Story ModeRIP3 — The Last HeroRIP3 — The Last Hero combines the dynamics of a hardcore shooter while preserving the elusive classic arcade appeal and never lets up on the intense action. Every level presents a new challenge requiring you to not only prove your sharp-shooting but to think and act tactically.The terrain and environments must be employed to survive waves of adversaries but since all in-game objects are destructible you must think fast. Your hero will travel all over the world from the African jungle to the Arctic snow through secret labs and bunkers in the streets and skyscrapers of Metropolis city and also go into deep space using a hijacked spaceship.100 levels of arcade shooting action6 unique playable characters with varied and powerful skills to developA huge arsenal of destructive weaponry each with 2 shooting modesCapture and control military vehicles including Tanks Helicopters and Battle TurretsFully destructible battlefield - all the objects can be damaged and destroyedIncludes a space adventure minigame where you pilot the Vostok-23 starship12 Huge challenging bosses evoke classic arcade gameplay3 difficulty level settings to increase the intensitySpecial bonuses and secrets are scattered throughout the gameCooperative multiplayer for two players to battle against the enemy hordesMultiplayer death-match for up to 6 players over LAN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  5

In [49]:
train_data['DemoCount'].value_counts()

DemoCount
0    10357
1      998
2        2
Name: count, dtype: int64

In [ ]:
shitty_columns = ['ResponseName', 'QueryName', 'QueryID', 'ResponseID', 'ReleaseDate', 'SupportEmail',
                   'SupportURL', 'ExtUserAcctNotice', 'LegalNotice', 'Website', 'RequiredAge', 'AboutText',
                   'HeaderImage', 'Background', 'DRMNotice', 'RequiredAge', ] # Doesn't have meaning or most of its values are nulls or 0s
text_columns =['AboutText', 'Reviews', 'DetailedDescrip', 'ShortDescrip'] # may have meaning, requires text processing or embeddings

In [ ]:
train_data['PriceInitial'][train_data['IsFree'] == True].head(15)

In [ ]:
train_data[train_data['PriceInitial'] == True].head(15)

In [45]:
train_data['DRMNotice'].value_counts()

DRMNotice
                                                                                                                             11287
Reality Pump                                                                                                                     9
Requires a Kalypso account                                                                                                       4
SecuROM(tm)                                                                                                                      3
SecuROM(tm)50 machine activation limit                                                                                           3
Games for Windows Live                                                                                                           3
Act Control5 machine activation limit                                                                                            3
Kalypso Launcher (Account registration optional)                                                                                 3
Serial key& Account linking                                                                                                      3
Denuvo Antitamper                                                                                                                3
TAGES(tm)3 machine activation limit                                                                                              2
Microsoft Games for Windows Live                                                                                                 2
Requires a free Kalypso account                                                                                                  2
simple key                                                                                                                       2
Seventh Knight3 different computers (with unlimited re-activations on each one) machine activation limit                         2
Reality Pump3 machine activation limit                                                                                           1
SecuROM(tm)4 machine activation limit                                                                                            1
SecuROM(tm)Unlimited machine activations                                                                                         1
Activation codeRenewal on request 5 machine activation limit                                                                     1
Tages Solidshield3 machine activation limit                                                                                      1
Themida5 machine activation limit                                                                                                1
SecuROM(tm)5 machine activation limit                                                                                            1
TAGES Solidshield5 machine activation limit                                                                                      1
Ubisofts Online Services Platform. Ubisoft requires a permanent Internet connection to play this video game at all times.        1
Tages Solidshield5 machine activation limit                                                                                      1
GameShield                                                                                                                       1
No 3rd Party DRM                                                                                                                 1
Games for Windows Live1 / GFWL Account machine activation limit                                                                  1
Games for Windows LiveOne per GFWL Account machine activation limit                                                              1
DRM Free!                                                                                                                        1
Uplay                                                                                                                            1
Cakewalk: E-mailNo machine activation limit                                                                                      1
Eversim3 different computers (with unlimited re-activations on each one) machine activation limit                                1
Uplay Account Required                                                                                                           1
FXpansion online activation3 Activations concurrent machine activation limit                                                     1
SecuROM(tm) Game For Windows Live                                                                                                1
Cakewalk: E-MailNo machine activation limit                                                                                      1
Reality Pump DLM V2none machine activation limit                                                                                 1
Trend Redaktions- und Verlagsgesellschaft mbH                                                                                    1
valve                                                                                                                            1
Denuvo Antitamper5 different PC within a day machine activation limit                                                            1
Name: count, dtype: int64

In [39]:
train_data[train_data['IsFree'] == True].sort_values(by='PriceFinal', ascending=False)

,QueryID,ResponseID,QueryName,ResponseName,ReleaseDate,RequiredAge,DemoCount,DeveloperCount,DLCCount,Metacritic,MovieCount,PackageCount,RecommendationCount,PublisherCount,ScreenshotCount,SteamSpyOwners,SteamSpyOwnersVariance,SteamSpyPlayersEstimate,SteamSpyPlayersVariance,AchievementCount,AchievementHighlightedCount,ControllerSupport,IsFree,FreeVerAvail,PurchaseAvail,SubscriptionAvail,PlatformWindows,PlatformLinux,PlatformMac,PCReqsHaveMin,PCReqsHaveRec,LinuxReqsHaveMin,LinuxReqsHaveRec,MacReqsHaveMin,MacReqsHaveRec,CategorySinglePlayer,CategoryMultiplayer,CategoryCoop,CategoryMMO,CategoryInAppPurchase,CategoryIncludeSrcSDK,CategoryIncludeLevelEditor,CategoryVRSupport,GenreIsNonGame,GenreIsIndie,GenreIsAction,GenreIsAdventure,GenreIsCasual,GenreIsStrategy,GenreIsRPG,GenreIsSimulation,GenreIsEarlyAccess,GenreIsFreeToPlay,GenreIsSports,GenreIsRacing,GenreIsMassivelyMultiplayer,PriceCurrency,PriceInitial,PriceFinal,SupportEmail,SupportURL,AboutText,Background,ShortDescrip,DetailedDescrip,DRMNotice,ExtUserAcctNotice,HeaderImage,LegalNotice,Reviews,SupportedLanguages,Website,PCMinReqsText,PCRecReqsText,LinuxMinReqsText,LinuxRecReqsText,MacMinReqsText,MacRecReqsText
2810,281900,281900,Indie Graphics Bundle,Indie Graphics Bundle - Royalty Free Sprites,May 6 2014,0,0,1,0,0,2,1,0,1,30,0,0,0,0,0,0,False,True,False,True,False,True,False,True,True,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,USD,99.99,99.99,contact@roencia.com,http://www.roencia.com/contactus.html,*This package represents the final version tha...,http://cdn.akamai.steamstatic.com/steam/apps/2...,Create your own Royalty Free Commercial Assets...,*This package represents the final version tha...,,,http://cdn.akamai.steamstatic.com/steam/apps/2...,,,English,http://www.graphicsforgames.com,Minimum:OS: Windows 2000 / XP / Vista / 7 / 8P...,,,,Minimum:OS: AnyStorage: 10 GB available spaceA...,
973,47400,47400,Stronghold 3,Stronghold 3 Gold,May 25 2012,0,0,1,0,0,5,1,2326,1,25,719192,22176,626827,20705,0,0,False,True,False,True,False,True,True,True,True,True,True,False,True,False,True,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,USD,29.99,29.99,,http://www.fireflyworlds.com/index.php?option=...,Stronghold 3 is the long-awaited third install...,http://cdn.akamai.steamstatic.com/steam/apps/4...,Stronghold 3 Gold has been updated to patch 1....,Stronghold 3 is the long-awaited third install...,,,http://cdn.akamai.steamstatic.com/steam/apps/4...,All trademarks referenced herein are the prope...,,English French German Italian Spanish,http://mlgames.com,Minimum:OS: Windows(r) XP SP3/ Windows(r) Vist...,Recommended:OS: Windows(r) Vista SP2/ Windows(...,OS: Linux Ubuntu 14.10 Mint 17 supported ...,,OS: 10.6.8 and above Processor:...,
1306,200980,200980,Geneforge 2,Geneforge 2,Jul 1 2003,0,0,1,0,0,0,1,0,1,5,95593,8091,6995,2189,0,0,False,True,False,True,False,True,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,False,False,False,False,USD,19.99,19.99,support@spiderwebsoftware.com,,Geneforge 2 is an Indie fantasy role-playing a...,http://cdn.akamai.steamstatic.com/steam/apps/2...,,Geneforge 2 is an Indie fantasy role-playing a...,,,http://cdn.akamai.steamstatic.com/steam/apps/2...,,,English,http://www.spiderwebsoftware.com,Operating system:Windows® XP / Vista™ / Window...,,,,,
1307,200990,200990,Geneforge 3,Geneforge 3,Apr 1 2005,0,0,1,0,0,0,1,0,1,5,95593,8091,4484,1752,0,0,False,True,False,True,False,True,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,False,False,False,False,USD,19.99,19.99,support@spiderwebsoftware.com,,Geneforge 3 is an Indie fantasy role-playing a...,http://cdn.akamai.steamstatic.com/steam/apps/2...,,Geneforge 3 is an Indie fantasy role-playing a...,,,http://cdn.akamai.steamstatic.com/steam/apps/2...,,,English,http://www.spiderwebsoftware.com/,Operating system:Windows® XP / Vista™ / Window...,,,,,
1308,201000,201000,Geneforge 4,Geneforge 4: Rebellion,Nov 1 2006,0,0,1,0,0,0,1,0,1,6,95593,8091,4125,1681,0,0,False,True,False,True,False,True,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,True,False,False,False,False,False,False,USD,19.99,19.99,support@spiderwebsoftware.com,,Geneforge 4: Rebellion is an Indie fantasy rol...,http://cdn.akamai.steamstatic.com/steam/apps/2...,,Geneforge 4: Rebellion is an Indie fantasy rol...,,,http://cdn.akamai.steamstatic.com/steam/apps/2...,,,English,http://www.spiderwebsoftware.com/,Operating system:Windows® XP / Vista™ / Window...,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4950,355070,355070,TDP5 Arena 3D,TDP5 Arena 3D,Mar 26 2015,0,0,1,0,0,1,1,173,1,6,178094,11043,59903,6405,0,0,False,True,True,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,True,,0.00,0.00,support@javelin.ee,https://javelinou.zendesk.com/,TDP5: Arena - the outstanding Free-To-Play 3D ...,http://cdn.akamai.steamstatic.com/steam/apps/3...,TDP5: Arena - the outstanding Free-To-Play 3D ...,TDP5: Arena - the outstanding Free-To-Play 3D ...,,,http://cdn.akamai.steamstatic.com/steam/apps/3...,,,English* Russian*languages with full audio sup...,http://www.tdp5.com/,Minimum:OS: Windows XP SP2 or higherProcessor:...,,,,,
4967,355500,355500,Leadwerks Game Launcher,Leadwerks Game Launcher,Aug 24 2015,0,0,1,0,0,1,0,0,1,34,69050,6877,10940,2737,0,0,True,True,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,,0.00,0.00,,http://www.leadwerks.com/werkspace/page/Compan...,Leadwerks Game Launcher lets you play a variet...,http://cdn.akamai.steamstatic.com/steam/apps/3...,Leadwerks Game Launcher lets you play a variet...,Leadwerks Game Launcher lets you play a variet...,,,http://cdn.akamai.steamstatic.com/steam/apps/3...,,,English,http://www.leadwerks.com,Minimum:OS: Windows Vista 7 8 8.1 or 10Process...,,,,,
4979,355840,355840,Survarium,Survarium,Apr 2 2015,0,0,1,7,0,3,0,12247,1,19,3092704,45836,1742202,34466,73,10,False,True,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,True,False,False,False,True,False,True,True,False,False,True,,0.00,0.00,support@survarium.com,https://support.survarium.com/,Join SURVARIUM Beta Now and Start Playing For ...,http://cdn.akamai.steamstatic.com/steam/apps/3...,Survarium is a post-apocalyptic online FPS gam...,New DLC AvailableGet your new Vepr Molot Pack ...,,,http://cdn.akamai.steamstatic.com/steam/apps/3...,(c) VOSTOK GAMES. SURVARIUM INC. 2012-2015,Weve all fallen hopelessly in love with ruined...,English* German Polish Russian* Ukrainian* Fre...,https://survarium.com,Minimum:OS: Windows Vista (Service Pack 2 + Pl...,,,,,
4990,356130,356130,Heroes of Scene,Heroes of Scene,Aug 26 2015,0,0,1,0,0,1,0,642,1,10,255753,13232,153344,10247,13,10,False,True,False,False,False,True,False,False,True,True,True,True,True,True,True,True,False,True,False,False,False,False,False,True,False,False,False,True,False,False,False,True,False,False,True,,0.00,0.00,,http://heroesofscene.com/,Heroes of scene is a multiplayer strategy game...,http://cdn.akamai.steamstatic.com/steam/apps/3...,Heroes of scene is a multiplayer strategy game...,Heroes of scene is a multiplayer strategy game...,,,http://cdn.akamai.steamstatic.com/steam/apps/3...,,,English* Russian**languages with full audio su...,http://heroesofscene.com/,Minimum:OS: Windows XPProcessor: 1.7 GHzMemory...,Recommended:OS: Windows 7Processor: 2.0 GHzMem...,Minimum:OS: Ubuntu 13.04 Raring Ringtail or be...,Recommended:OS: Ubuntu 13.04 Raring Ringtail o...,Minimum:OS: Leopard 10.5 or betterProcessor: 1...,Recommended:OS: Snow Leopard 10.6 or betterPro...
4877,352700,352700,Subspace Continuum,Subspace Continuum,Jul 3 2015,0,0,2,0,0,3,0,344,1,8,126980,9325,48424,5759,0,0,False,True,False,False,False,True,False,False,True,False,False,False,True,False,False,True,True,True,False,False,False,False,False,False,True,False,True,False,False,False,False,True,False,False,True,,0.00,0.00,info@subspace-continuum.com,http://subspace-continuum.com,Subspace Continuum is a player-maintained onli...,http://cdn.akamai.steamstatic.com/steam/apps/3...,Subspace Continuum is the longest running mass...,Subspace Continuum is a player-maintained onli...,,,http://cdn.akamai.steamstatic.com/steam/apps/3...,,If youre looking for a fun multiplayer action ...,English,http://www.subspace-continuum.com,Minimum:OS: Windows XPProcessor: Intel 2 DuoMe...,,,,Minimum:OS: OSX LionProcessor: Intel 2 DuoMemo...,

In [30]:
train_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 11357 entries, 0 to 11356
Data columns (total 78 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   QueryID                      11357 non-null  int64
 1   ResponseID                   11357 non-null  int64
 2   QueryName                    11356 non-null  str
 3   ResponseName                 11357 non-null  str
 4   ReleaseDate                  11357 non-null  str
 5   RequiredAge                  11357 non-null  int64
 6   DemoCount                    11357 non-null  int64
 7   DeveloperCount               11357 non-null  int64
 8   DLCCount                     11357 non-null  int64
 9   Metacritic                   11357 non-null  int64
 10  MovieCount                   11357 non-null  int64
 11  PackageCount                 11357 non-null  int64
 12  RecommendationCount          11357 non-null  int64
 13  PublisherCount               11357 non-null  int64
 14  ScreenshotCount              11357 non-null  int64
 15  SteamSpyOwners               11357 non-null  int64
 16  SteamSpyOwnersVariance       11357 non-null  int64
 17  SteamSpyPlayersEstimate      11357 non-null  int64
 18  SteamSpyPlayersVariance      11357 non-null  int64
 19  AchievementCount             11357 non-null  int64
 20  AchievementHighlightedCount  11357 non-null  int64
 21  ControllerSupport            11357 non-null  bool
 22  IsFree                       11357 non-null  bool
 23  FreeVerAvail                 11357 non-null  bool
 24  PurchaseAvail                11357 non-null  bool
 25  SubscriptionAvail            11357 non-null  bool
 26  PlatformWindows              11357 non-null  bool
 27  PlatformLinux                11357 non-null  bool
 28  PlatformMac                  11357 non-null  bool
 29  PCReqsHaveMin                11357 non-null  bool
 30  PCReqsHaveRec                11357 non-null  bool
 31  LinuxReqsHaveMin             11357 non-null  bool
 32  LinuxReqsHaveRec             11357 non-null  bool
 33  MacReqsHaveMin               11357 non-null  bool
 34  MacReqsHaveRec               11357 non-null  bool
 35  CategorySinglePlayer         11357 non-null  bool
 36  CategoryMultiplayer          11357 non-null  bool
 37  CategoryCoop                 11357 non-null  bool
 38  CategoryMMO                  11357 non-null  bool
 39  CategoryInAppPurchase        11357 non-null  bool
 40  CategoryIncludeSrcSDK        11357 non-null  bool
 41  CategoryIncludeLevelEditor   11357 non-null  bool
 42  CategoryVRSupport            11357 non-null  bool
 43  GenreIsNonGame               11357 non-null  bool
 44  GenreIsIndie                 11357 non-null  bool
 45  GenreIsAction                11357 non-null  bool
 46  GenreIsAdventure             11357 non-null  bool
 47  GenreIsCasual                11357 non-null  bool
 48  GenreIsStrategy              11357 non-null  bool
 49  GenreIsRPG                   11357 non-null  bool
 50  GenreIsSimulation            11357 non-null  bool
 51  GenreIsEarlyAccess           11357 non-null  bool
 52  GenreIsFreeToPlay            11357 non-null  bool
 53  GenreIsSports                11357 non-null  bool
 54  GenreIsRacing                11357 non-null  bool
 55  GenreIsMassivelyMultiplayer  11357 non-null  bool
 56  PriceCurrency                11357 non-null  str
 57  PriceInitial                 11357 non-null  float64
 58  PriceFinal                   11357 non-null  float64
 59  SupportEmail                 11355 non-null  str
 60  SupportURL                   11356 non-null  str
 61  AboutText                    11357 non-null  str
 62  Background                   11357 non-null  str
 63  ShortDescrip                 11357 non-null  str
 64  DetailedDescrip              11357 non-null  str
 65  DRMNotice                    11357 non-null  str
 66  ExtUserAcctNotice            11357 non-null  str
 67  HeaderImage                  11357 non-null  str
 68  LegalNotice                  11356 non-null  str
 69  Reviews                      11357 non-null  str
 70  SupportedLanguages           11357 non-null  str
 71  Website                      8644 non-null   str
 72  PCMinReqsText                11357 non-null  str
 73  PCRecReqsText                11357 non-null  str
 74  LinuxMinReqsText             11357 non-null  str
 75  LinuxRecReqsText             11357 non-null  str
 76  MacMinReqsText               11357 non-null  str
 77  MacRecReqsText               11357 non-null  str
dtypes: bool(35), float64(2), int64(18), str(23)
memory usage: 4.1 MB

In [28]:
needed_columns = train_data.columns.difference(shitty_columns)
needed_columns

Index(['AboutText', 'AchievementCount', 'AchievementHighlightedCount',
       'Background', 'CategoryCoop', 'CategoryInAppPurchase',
       'CategoryIncludeLevelEditor', 'CategoryIncludeSrcSDK', 'CategoryMMO',
       'CategoryMultiplayer', 'CategorySinglePlayer', 'CategoryVRSupport',
       'ControllerSupport', 'DLCCount', 'DRMNotice', 'DemoCount',
       'DetailedDescrip', 'DeveloperCount', 'FreeVerAvail', 'GenreIsAction',
       'GenreIsAdventure', 'GenreIsCasual', 'GenreIsEarlyAccess',
       'GenreIsFreeToPlay', 'GenreIsIndie', 'GenreIsMassivelyMultiplayer',
       'GenreIsNonGame', 'GenreIsRPG', 'GenreIsRacing', 'GenreIsSimulation',
       'GenreIsSports', 'GenreIsStrategy', 'HeaderImage', 'IsFree',
       'LinuxMinReqsText', 'LinuxRecReqsText', 'LinuxReqsHaveMin',
       'LinuxReqsHaveRec', 'MacMinReqsText', 'MacRecReqsText',
       'MacReqsHaveMin', 'MacReqsHaveRec', 'Metacritic', 'MovieCount',
       'PCMinReqsText', 'PCRecReqsText', 'PCReqsHaveMin', 'PCReqsHaveRec',
       'PackageCount', 'PlatformLinux', 'PlatformMac', 'PlatformWindows',
       'PriceCurrency', 'PriceFinal', 'PriceInitial', 'PublisherCount',
       'PurchaseAvail', 'RecommendationCount', 'Reviews', 'ScreenshotCount',
       'ShortDescrip', 'SteamSpyOwners', 'SteamSpyOwnersVariance',
       'SteamSpyPlayersEstimate', 'SteamSpyPlayersVariance',
       'SubscriptionAvail', 'SupportedLanguages'],
      dtype='str')